apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv-last
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc  
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02e1291083e3fb51d  
